runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:vcNK5ZQ1TLnkzNpgEi56Trn1kgZBKbmrhfURcvYfacw=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
